flutasapp/urls.py
from django.contrib import admin
from django.urls import path
from consumo_gasolina import views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.search, name='home'),
    path('data_policy/', views.data_policy, name='data_policy'),
    path('data_policy_en/', views.data_policy_en, name='data_policy_en'),
    path('compare/', views.compare_vehicles, name='compare_vehicles'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.singin, name='login'),
    path('password_reset/', views.password_reset_request, name='password_reset'),
    path('password_reset/done/', views.password_reseted, name='password_reset_done'),
    path('change_password/', views.change_password, name='change_password'),
    path('change_password/done/', views.changed_password, name='password_change_done'),
    path('logout/', views.signout, name='logout'),
    path('my_account/', views.my_account, name='my_account'),
    path('search_vehicles/', views.search_vehicles, name='search_vehicles'),
    path('get_selected_vehicles/', views.get_selected_vehicles, name='get_selected_vehicles'),
    path('compare/analyze/', views.analyze_selected_vehicles, name='analyze_selected_vehicles'),
    path('update_selected_vehicles/', views.update_selected_vehicles, name='update_selected_vehicles'),
    path('calculate_fuel_cost/', views.calculate_fuel_cost, name='calculate_fuel_cost'),
    path('create_vehicle/', views.create_vehicle, name='create_vehicle'),
    path('create_route/', views.create_route, name='create_route'),
    path('heatmap/', views.heatmap, name='heatmap'),
    path('clustermap/', views.clustermap, name='clustermap'),
    path('analyze-vehicles/', views.analyze_vehicles, name='analyze_vehicles'),
    path('vehicles/', views.view_vehicles, name='view_vehicles'),
    path('vehicles/<int:vehicle_id>/edit/', views.edit_vehicle, name='edit_vehicle'),
    path('vehicles/<int:vehicle_id>/delete/', views.delete_vehicle, name='delete_vehicle'),
    path('routes/', views.view_routes, name='view_routes'), 
    path('routes/<int:route_id>/edit/', views.edit_route, name='edit_route'), 
    path('routes/<int:route_id>/delete/', views.delete_route, name='delete_route'),
    path('routes/<int:route_id>/complete/', views.complete_route, name='complete_route'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

consumo_gasolina/models.py
from django.db import models
from django.contrib.auth.models import User



# Create your models here.
class Vehicle(models.Model):
    """
    Modelo para almacenar la información de los vehículos de los usuarios.
    
    Atributos:
        owner (ForeignKey): Usuario propietario del vehículo.
        brand (CharField): Marca del vehículo.
        sub_brand (CharField): Submarca del vehículo.
        model_year (PositiveIntegerField): Año de fabricación del vehículo.
        version (CharField): Versión del vehículo.
        fuel_efficiency (FloatField): Rendimiento de combustible del vehículo.
        fuel_type (CharField): Tipo de combustible del vehículo.
        license_plate (CharField): Placa del vehículo.
    """
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    brand = models.CharField(max_length=100)
    sub_brand = models.CharField(max_length=100)
    model_year = models.PositiveIntegerField()
    version = models.CharField(max_length=100)
    fuel_efficiency = models.FloatField()
    fuel_type = models.CharField(max_length=8)
    license_plate = models.CharField(max_length=20)

    def __str__(self):
        return f"brand:{self.brand} sub_brand:{self.sub_brand} version:{self.version} model_year:({self.model_year}) fuel_efficiency:{self.fuel_efficiency} fuel_type:{self.fuel_type} license_plate:{self.license_plate}"
    
    
class Route(models.Model):
    """
    Modelo para almacenar la información de las rutas de los usuarios.
    
    Atributos:
        owner (ForeignKey): Usuario creador de la ruta.
        start (CharField): Punto de inicio de la ruta.
        end (CharField): Punto de destino de la ruta.
        start_coords (CharField): Coordenadas del punto de inicio de la ruta.
        end_coords (CharField): Coordenadas del punto de destino de la ruta.
        date_created (DateTimeField): Fecha y hora de creación de la ruta.
        description (TextField): Descripción de la ruta.
        date_completed (DateTimeField): Fecha y hora de finalización de la ruta.
    """
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    start = models.CharField(max_length=255)
    end = models.CharField(max_length=255)
    start_coords = models.CharField(max_length=255)
    end_coords = models.CharField(max_length=255)
    date_created = models.DateTimeField(auto_now_add=True)
    description = models.TextField(blank=True)
    date_completed = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"start:{self.start} - end:{self.end} date_c({self.date_created}) date_f({self.date_completed}) start_coords:{self.start_coords} end_coords:{self.end_coords}"

consumo_gasolina/views.py
# Importa los módulos para el funcionamiento de las vistas de Django
import base64
import json
from datetime import timezone
from io import BytesIO

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render

# Importa los modelos y formularios personalizados
from consumo_gasolina.models import Route, Vehicle
from flutasapp.forms import (
    ChangePasswordForm,
    FuelCostForm,
    LoginForm,
    PasswordResetRequestForm,
    RouteForm,
    SignUpForm,
    VehicleForm,
    VehicleSearchForm,
)

# Importa la clases de utils para buscar y analizar vehículos
from utils.analyze_vehicles import VehicleAnalyzer
from utils.calculate_cost import CostCalculator
from utils.draw_graphs import Drawer
from utils.geo_utils import GeoUtils
from utils.search_vehicle import VehicleSearcher

# Importa la función para enviar correos electrónicos
from .courier import send_password_reset_email

# Crea una instancia de VehicleSearcher para buscar vehículos en el dataset
SEARCHER = VehicleSearcher()

# Crea una instancia de VehicleAnalyzer para analizar la info de los vehículos
ANALYZER = VehicleAnalyzer()

# Crea una instancia de CostCalculator para calcular el costo de combustible
CALCULATOR = CostCalculator()

# Crea una instancia de GeoUtils para geocodificar direcciones
GEOUTILS = GeoUtils()

# Crear una instancia de Drawer para dibujar gráficas
DRAWER = Drawer()



# Create your views here.
def search(request):
    """
    Vista para la página de inicio.

    Args:
        request (HttpRequest): Solicitud HTTP que se recibe desde el cliente.

    Returns:
        HttpResponse: Respuesta HTTP que renderiza la página de inicio con 
        el formulario de búsqueda.
    """
    if request.method == 'POST':
        form = VehicleSearchForm(request.POST)
        if form.is_valid():
            # Buscar vehículos en el dataset con el objeto VehicleSearcher
            vehicles = SEARCHER.search(
                query=form.cleaned_data).to_dict(orient='records')
                                    
            # Renderizar la página de inicio con los resultados de la búsqueda
            return render(
                request, 'search.html', {'form': form, 'vehicles': vehicles})
    else:
        # Inicializar el formulario de búsqueda
        form = VehicleSearchForm()
        
        # Renderizar una búsqueda vacía
        vehicles = SEARCHER.search(query={}).to_dict(orient='records')
    return render(request, 'search.html', {'form': form, 'vehicles': vehicles})



def signup(request):
    """
    Función que permite a un usuario registrarse en el sistema.

    Args:
        request (HttpRequest): Solicitud HTTP que se recibe desde el cliente.

    Returns:
        HttpResponse: Respuesta HTTP que se enviará al cliente.
    """
    # Si la solicitud es POST, se procesa la información del formulario
    if request.method == "POST":
        # Se crea un formulario con la información recibida
        form = SignUpForm(request.POST)

        # Si el formulario es válido, se guarda el usuario en la base de datos
        if form.is_valid():
            # Guarda el usuario en la base de datos
            form.save()

            # Redirige al usuario a la página de inicio
            return redirect("login")
    else:
        # Si la solicitud no es POST, se crea un formulario en blanco
        form = SignUpForm()

    # Si el formulario no es válido, los errores se agregarán al formulario
    return render(request, "signup.html", {"form": form})

def singin(request):
    """
    Función que permite a un usuario iniciar sesión en el sistema.

    Args:
        request (HttpRequest): Solicitud HTTP que se recibe desde el cliente.

    Returns:
        HttpResponse: Respuesta HTTP que se enviará al cliente.

    Raises:
        ValidationError: Si el usuario o la contraseña son incorrectos.
    """
    if request.method == "POST":
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, "Inicio de sesión exitoso.")
                return redirect("home")
            else:
                messages.error(request, 
                               "Nombre de usuario o contraseña incorrectos.")
        else:
            messages.error(request, 
                           "Por favor corrija los errores en el formulario.")
    else:
        form = LoginForm(request)
    return render(request, "signin.html", {"form": form})

def signout(request):
    """
    Función que permite a un usuario cerrar sesión en el sistema.

    Args:
        request (HttpRequest): Solicitud HTTP que se recibe desde el cliente.

    Returns:
        HttpResponse: Respuesta HTTP que se enviará al cliente.
    """
    logout(request)
    messages.success(request, "Cierre de sesión exitoso.")
    return redirect("home")

def password_reset_request(request):
    """
    Vista para manejar solicitudes de restablecimiento de contraseña.

    Args:
        request (HttpRequest): Solicitud HTTP que se recibe desde el cliente.

    Returns:
        HttpResponse: Respuesta HTTP que renderiza el formulario de solicitud
        de restablecimiento de contraseña o redirige después de enviar 
        el correo.
    """
    if request.method == "POST":
        form = PasswordResetRequestForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get("email")
            associated_users = User.objects.filter(email=email)
            if associated_users.exists():
                for user in associated_users:
                    # Genera una contraseña temporal segura
                    temporary_password = (
                        PasswordResetRequestForm.generate_temporary_password()
                    )
                    user.password = make_password(str(temporary_password))

                    # Guarda la contraseña temporal en la base de datos
                    user.save()

                    # Obtener el nombre de usuario
                    username = user.username

                    # Envíar la contraseña temporal al correo del usuario
                    send_password_reset_email(email, 
                                              username, 
                                              str(temporary_password))

            # Redirige al usuario a la página de restablecimiento de
            # contraseña enviada
            return redirect("password_reset_done")
    else:
        form = PasswordResetRequestForm()
    return render(request, "password_reset_form.html", {"form": form})

def password_reseted(request):
    """
    Vista que se muestra después de enviar un correo electrónico de
    restablecimiento de contraseña.

    Args:
        request (HttpRequest): Solicitud HTTP que se recibe desde el cliente.

    Returns:
        HttpResponse: Respuesta HTTP que renderiza la página de 
        restablecimiento de contraseña enviada.
    """
    return render(request, "password_reset_done.html")

@login_required

def change_password(request):
    """
    Vista para manejar el cambio de contraseña del usuario autenticado.

    Args:
        request (HttpRequest): Solicitud HTTP que se recibe desde el cliente.

    Returns:
        HttpResponse: Respuesta HTTP que renderiza el formulario de cambio
        de contraseña o redirige después de cambiar la contraseña.
    """
    if request.method == "POST":
        form = ChangePasswordForm(request.POST, user=request.user)
        if form.is_valid():
            # Cambiar la contraseña del usuario
            new_password = form.cleaned_data.get("new_password2")
            request.user.set_password(new_password)
            request.user.save()

            # Actualizar la sesión evitar desconectar al usuario
            update_session_auth_hash(request, request.user)

            # Redirigir al usuario a la página de cambio de contraseña exitoso
            return redirect("password_change_done")
    else:
        # Enviar el formulario de cambio de contraseña a la vista
        form = ChangePasswordForm(user=request.user)
    return render(request, "change_password.html", {"form": form})

def changed_password(request):
    """
    Vista que se muestra después de cambiar la contraseña del usuario.

    Args:
        request (HttpRequest): Solicitud HTTP que se recibe desde el cliente.

    Returns:
        HttpResponse: Respuesta HTTP que renderiza la página de cambio de
        contraseña exitoso.
    """
    # Renderiza la página de cambio de contraseña exitoso
    return render(request, "changed_password.html")


@login_required
def my_account(request):
    """
    Vista para mostrar la información del usuario en la página "Mi Cuenta".

    Args:
        request (HttpRequest): Solicitud HTTP que se recibe desde el cliente.

    Returns:
        HttpResponse: Respuesta HTTP que renderiza la página "Mi Cuenta".
    """
    user = request.user
    return render(request, "my_account.html", {"user": user})

def search_vehicles(request):
    """
    Vista que maneja las solicitudes de búsqueda de vehículos para mostrarlas
    en la página de comparación de vehículos sin necesidad de recargar la 
    página.
    
    Args:
        request (HttpRequest): Solicitud HTTP que se recibe desde el cliente.
        
    Returns:
        JsonResponse: Respuesta JSON que contiene los vehículos encontrados."""
    if request.method == 'POST':

consumo_gasolina/templates/analyze_selected_vehicles.html
{% extends 'base.html' %}

{% block title %}Analizar Vehículos{% endblock %}

{% block content %}
<h1>Tabla de comparación</h1>

<table border="1">
    <thead>
        <tr>
            <th>Marca</th>
            <th>Submarca</th>
            <th>Modelo</th>
            <th>Versión</th>
            <th>Transmisión</th>
            <th>Combustible</th>
            <th>Categoría</th>
            <th>Cilindros</th>
            <th>Potencia (HP)</th>
            <th>Tamaño (L)</th>
            <th>Rendimiento Ciudad (km/L)</th>
            <th>Rendimiento Carretera (km/L)</th>
            <th>Rendimiento Combinado (km/L)</th>
            <th>CO2 (g/km)</th>
            <th>NOx (g/km)</th>
            <th>Calificación gases de efecto invernadero (10: Eficiente)</th>
            <th>Calificación contaminación del aire (10: Más limpio)</th>
        </tr>
    </thead>
    <tbody>
        {% for vehicle in selected_vehicles %}
        <tr>
            <td>{{ vehicle.marca }}</td>
            <td>{{ vehicle.submarca }}</td>
            <td>{{ vehicle.modelo }}</td>
            <td>{{ vehicle.version }}</td>
            <td>{{ vehicle.transmision }}</td>
            <td>{{ vehicle.combustible }}</td>
            <td>{{ vehicle.categoria }}</td>
            <td>{{ vehicle.cilindros }}</td>
            <td>{{ vehicle.potencia }}</td>
            <td>{{ vehicle.tamano }}</td>
            <td>{{ vehicle.rendimiento_ciudad }}</td>
            <td>{{ vehicle.rendimiento_carretera }}</td>
            <td>{{ vehicle.rendimiento_combinado }}</td>
            <td>{{ vehicle.co2 }}</td>
            <td>{{ vehicle.nox }}</td>
            <td>{{ vehicle.efecto_invernadero }}</td>
            <td>{% if vehicle.contaminacion_aire == '?' %}0{% else %}{{ vehicle.contaminacion_aire }}{% endif %}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<h2>Diferencias entre Vehículos</h2>
<table border="1">
    <tr>
      <th></th> <!-- Espacio vacío para el índice -->
      {% for col in analysis_vehicles.columns %}
        <th>{{ col }}</th> <!-- Nombres de las columnas -->
      {% endfor %}
    </tr>
    {% for index, row in analysis_vehicles.iterrows %}
      <tr>
        <td>{{ index }}</td> <!-- Nombre del índice -->
        {% for cell in row %}
            {% if index in columns_with_percentage and cell < 0 %}
                <td>{{ cell }}%</td> <!-- Contenido de la fila -->
            {% else %}
                <td>{{ cell }}</td> <!-- Contenido de la fila -->
            {% endif %}
        {% endfor %}
      </tr>
    {% endfor %}
</table>
<a href={% url 'home' %}>Regresar a la página principal</a>
<a href={% url 'compare_vehicles' %}>Comparar más vehículos</a>
{% endblock %}

consumo_gasolina/templates/analyze_vehicles.html
{% extends "base.html" %}

{% block title %}Analyze Vehicles{% endblock %}

{% block content %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Análisis de vehículos</title>
</head>
<body>
    <h2>Análisis de vehículos</h2>
    {% if sucessMessage %}
        <p>{{ sucessMessage }}</p>
        <div>
            <h3>Gráfico de eficiencia de combustible</h3>
            <img src="data:image/png;base64,{{ fuel_efficiency_bar_chart }}" alt="Gráfico de eficiencia de combustible">
        </div>

        <div>
            <h3>Gráfico de vehículos por marca</h3>
            <img src="data:image/png;base64,{{ vehicles_by_brand_pie_chart }}" alt="Gráfico de vehículos por marca">
        </div>

        <div>
            <h3>Distribución de eficiencia de combustible</h3>
            <img src="data:image/png;base64,{{ fuel_efficiency_distribution }}" alt="Distribución de eficiencia de combustible">
        </div>
    {% else %}
        <p>{{ errorMessage }}</p>
        <a href="{% url 'create_vehicle' %}">Crear vehículo</a>
        <a href="/consumo_gasolina/analyze_vehicles">Volver a intentar</a>
    {% endif %}
</body>
</html>

{% endblock %}

consumo_gasolina/templates/change_password.html
{% extends 'base.html' %}

{% block title %}Cambiar Contraseña{% endblock %}

{% block content %}

<!DOCTYPE html>
<html lang="en">
    <body>
    <h2>Cambiar Contraseña</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
    
        {% if form.errors %}
            <ul>
            {% for field, errors in form.errors.items %}
                {% for error in errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            {% endfor %}
            </ul>
        {% endif %}
    
        <button type="submit">Cambiar Contraseña</button>
    </form>
</body>
</html>

{% endblock %}

consumo_gasolina/templates/compare.html
{% extends 'base.html' %}
{% block title %}Comparar Vehículos{% endblock %}
{% block content %}
<h1>Comparar Vehículos</h1>
<div style="display: flex; justify-content: space-between;">
    <!-- Columna izquierda -->
    <div style="width: 48%;">
        <h2>Búsqueda de Vehículos</h2>
        <form id="VehicleSearchForm" method="post">
            {% csrf_token %}
            <div class="input-with-button">
                <label for="id_brand">Marca:</label>
                {{ form.brand }}
                <button type="button" onclick="clearInput('id_brand')">Limpiar</button>
            </div>
            <div class="input-with-button">
                <label for="id_sub_brand">Submarca:</label>
                {{ form.sub_brand }}
                <button type="button" onclick="clearInput('id_sub_brand')">Limpiar</button>
            </div>
            <div class="input-with-button">
                <label for="id_model_year">Modelo:</label>
                {{ form.model_year }}
                <button type="button" onclick="clearInput('id_model_year')">Limpiar</button>
            </div>
            <div class="input-with-button">
                <label for="id_version">Versión:</label>
                {{ form.version }}
                <button type="button" onclick="clearInput('id_version')">Limpiar</button>
            </div>
            <button type="button" onclick="searchVehicles()">Buscar</button>
        </form>
        <!-- Resultados de la Búsqueda -->
        <div id="search-results">
            <!-- Aquí se mostrarán los resultados de la búsqueda -->
        </div>
    </div>
    <!-- Columna derecha -->
    <div style="width: 48%;">
        <h2>Vehículos Seleccionados para Comparar:</h2>
        <ul id="selected-vehicles-list">
            <!-- Aquí se mostrarán los vehículos seleccionados -->
        </ul>
        <button type="button" onclick="compareSelectedVehicles()">Comparar</button>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    var vehiclesToCompare = [];

    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    const csrftoken = getCookie('csrftoken');

    function clearInput(inputId) {
        document.getElementById(inputId).value = '';
    }

    function searchVehicles() {
        var formData = $('#VehicleSearchForm').serialize();
        $.ajax({
            type: "POST",
            url: "{% url 'search_vehicles' %}",
            data: formData,
            headers: {
                'X-CSRFToken': csrftoken
            },
            success: function(response) {
                var searchResultsDiv = $('#search-results');
                searchResultsDiv.empty();
                var vehicles = response.vehicles;
                if (vehicles.length > 0) {
                    var resultsList = $('<ul></ul>');
                    vehicles.forEach(function(vehicle) {
                        var listItem = $('<li></li>').text(
                            vehicle.marca + ' ' + vehicle.submarca + ' ' + vehicle.modelo + ' ' + vehicle.version
                        );
                        var addButton = $('<button></button>').text('Añadir').click(function() {
                            addVehicleToCompare(vehicle);
                        });
                        listItem.append(addButton);
                        resultsList.append(listItem);
                    });
                    searchResultsDiv.append(resultsList);
                } else {
                    searchResultsDiv.text('No se encontraron vehículos.');
                }
            }
        });
    }

    function addVehicleToCompare(vehicle) {
        vehiclesToCompare.push(vehicle);
        updateSelectedVehiclesList();
    }

    function removeVehicle(index) {
        vehiclesToCompare.splice(index, 1);
        updateSelectedVehiclesList();
    }

    function updateSelectedVehiclesList() {
        var list = document.getElementById('selected-vehicles-list');
        list.innerHTML = '';
        vehiclesToCompare.forEach(function(vehicle, index) {
            var listItem = document.createElement('li');
            listItem.textContent = vehicle.marca + ' ' + vehicle.submarca + ' ' + vehicle.modelo + ' ' + vehicle.version;
            var removeButton = document.createElement('button');
            removeButton.textContent = 'Eliminar';
            removeButton.onclick = function() {
                removeVehicle(index);
            };
            listItem.appendChild(removeButton);
            list.appendChild(listItem);
        });

        // Enviar la lista de vehículos seleccionados al servidor
        $.ajax({
            type: "POST",
            url: "{% url 'update_selected_vehicles' %}",
            data: {
                selected_vehicles: JSON.stringify(vehiclesToCompare),
                csrfmiddlewaretoken: csrftoken
            },
            success: function(response) {
                console.log(response);
            }
        });
    }

    function compareSelectedVehicles() {
        $.ajax({
            type: "POST",
            url: "{% url 'get_selected_vehicles' %}",
            data: JSON.stringify(vehiclesToCompare),
            contentType: "application/json",
            headers: {
                'X-CSRFToken': csrftoken
            },
            success: function(response) {
                // Manejar la respuesta del servidor
                if (response.success) {
                    window.location.href = "{% url 'analyze_selected_vehicles' %}";
                } else {
                    alert('Error al comparar los vehículos.');
                }
            }
        });
    }
</script>
{% endblock %}

consumo_gasolina/templates/search.html
{% extends 'base.html' %}

{% block title %}Búsqueda de Vehículos{% endblock %}

{% block content %}

<h1>Búsqueda de Vehículos</h1>
<form id="VehicleSearchForm" method="post">
    {% csrf_token %}
    <!-- Agregar los campos del formulario junto con sus botones de limpieza -->
    <div class="input-with-button">
        <label for="id_brand">Marca:</label>
        {{ form.brand }}
        <button type="button" onclick="clearInput('id_brand')">Limpiar</button>
    </div>
    <div class="input-with-button">
        <label for="id_sub_brand">Submarca:</label>
        {{ form.sub_brand }}
        <button type="button" onclick="clearInput('id_sub_brand')">Limpiar</button>
    </div>
    <div class="input-with-button">
        <label for="id_model_year">Modelo:</label>
        {{ form.model_year }}
        <button type="button" onclick="clearInput('id_model_year')">Limpiar</button>
    </div>
    <div class="input-with-button">
        <label for="id_version">Versión:</label>
        {{ form.version }}
        <button type="button" onclick="clearInput('id_version')">Limpiar</button>
    </div>
    <button type="button" onclick="clearForm()">Limpiar Formulario</button>
    <button type="submit">Buscar</button>
</form>

<!-- Resultados de la búsqueda -->
{% if not vehicles.empty %}
    <h2>Resultados de la Búsqueda:</h2>
    <ul>
        {% for vehicle in vehicles %}
            <li>
                <strong>Marca:</strong> {{ vehicle.marca }}, 
                <strong>Submarca:</strong> {{ vehicle.submarca }},
                <strong>Año Modelo:</strong> {{ vehicle.modelo }}, 
                <strong>Versión:</strong> {{ vehicle.version }},
                <strong>Rendimiento en ciudad:</strong> {{ vehicle.rendimiento_ciudad }},
                <!-- Definir la sección de más detalles para mostrar -->
                <button type="button" onclick="showDetails('{{ vehicle.id }}')">Ver más</button>
                <div id="details_{{ vehicle.id }}" style="display: none;">
                    <!-- Se muestran más detalles del vehículo, como transmisión, cilindros, etc. -->
                    <strong>Transmisión:</strong> {{ vehicle.transmision }},
                    <strong>Cilindros:</strong> {{ vehicle.cilindros }},
                    <strong>Combustible:</strong> {{ vehicle.combustible }},
                    <strong>Rendimiento en carretera:</strong> {{ vehicle.rendimiento_carretera }},
                    <strong>Rendimiento combinado:</strong> {{ vehicle.rendimiento_combinado }},
                    <strong>Calificación efecto invernadero:</strong> {{ vehicle.efecto_invernadero }},
                    <strong>Calificación contaminación del aire:</strong> {{ vehicle.contaminacion_aire }},
                </div>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>Prueba haciendo una búsqueda</p>
{% endif %}

</body>

<script>
    function clearInput(inputId) {
        document.getElementById(inputId).value = '';
    }

    function clearForm(formId) {
        document.getElementById('id_brand').value = '';
        document.getElementById('id_sub_brand').value = '';
        document.getElementById('id_model_year').value = '';
        document.getElementById('id_version').value = '';
        document.getElementById("VehicleSearchForm").submit();
    }
    function showDetails(vehicleId) {
        var detailsDiv = document.getElementById('details_' + vehicleId);
        if (detailsDiv.style.display === 'none') {
            detailsDiv.style.display = 'block';
        } else {
            detailsDiv.style.display = 'none';
        }
    }
</script>

{% endblock %}